---
- name: "Python | {{ ansible_facts['distribution'] }} | Install packages"
  community.general.pacman:
    name:
      - python
      - python-pip
    state: present
  become: true
  when: can_install_packages | default(false)
