---
- name: "Python | {{ ansible_facts['distribution'] }} | Install packages"
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
    state: present
  become: true
  when: can_install_packages | default(false)
