---
- name: "Podman | Install Podman"
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: present
  become: true
  loop:
    - podman
  when: can_install_packages | default(false)

# install if WSL
- name: "Podman | Install Podman WSL Dependencies"
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: present
  become: true
  loop:
    - qemu-system-x86
  when:
    - can_install_packages | default(false)
    - ansible_host_environment_is_wsl

- name: "Podman | Package installation skipped"
  ansible.builtin.debug:
    msg: "Podman package installation skipped because sudo is unavailable."
  when: not (can_install_packages | default(false))
