---
- name: "Zsh | {{ ansible_facts['distribution'] }} | Install zsh packages"
  ansible.builtin.dnf:
    name:
      - zsh
      - git
      - fzf
      - zoxide
      - util-linux-user
    state: present
  become: true
  when: can_install_packages | default(false)

- name: "Zsh | {{ ansible_facts['distribution'] }} | Link global zshenv"
  ansible.builtin.file:
    src: "{{ role_path }}/files/global.zshenv"
    dest: /etc/zshenv
    state: link
    force: true
  become: true
  when: can_install_packages | default(false)
