---
- name: "Zsh | MacOSX | Install zsh packages"
  community.general.homebrew:
    name:
      - zsh
      - fzf
    state: present

- name: "Zsh | MacOSX | Register Homebrew zsh in /etc/shells"
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/zsh
    state: present
  become: true
  when: can_install_packages | default(false)

- name: "Zsh | MacOSX | Set default shell"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /opt/homebrew/bin/zsh
  become: true
  when:
    - zsh_default_shell | default(true)
    - can_install_packages | default(false)
