---
- name: "Zsh | {{ ansible_facts['distribution'] }} | Install zsh packages"
  ansible.builtin.apt:
    name:
      - zsh
      - git
      - fzf
    state: present
  become: true
  when: can_install_packages | default(false)

- name: "Zsh | {{ ansible_facts['distribution'] }} | Link global zshenv"
  ansible.builtin.file:
    src: "{{ role_path }}/files/global.zshenv"
    dest: /etc/zsh/zshenv
    state: link
    force: true
  become: true
  when: can_install_packages | default(false)

- name: "Zsh | {{ ansible_facts['distribution'] }} | Set default shell"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/zsh
  become: true
  when:
    - zsh_default_shell | default(true)
    - can_install_packages | default(false)
