---
- name: "Developer tools | Fedora | Install packages"
  ansible.builtin.dnf:
    name:
      - clang
      - clang-devel
      - cmake
      - fastfetch
      - gcc
      - gcc-c++
      - gitleaks
      - graphviz
      - hyperfine
      - java-25-openjdk
      - jq
      - libtool
      - make
      - pkgconf-pkg-config
    state: present
  become: true
  when: can_install_packages | default(false)
