---
- name: "Developer tools | Ubuntu | Install packages"
  ansible.builtin.apt:
    name:
      - build-essential
      - clang
      - cmake
      - fastfetch
      - graphviz
      - hyperfine
      - jq
      - libtool
      - pkg-config
    state: present
    update_cache: true
  become: true
  when: can_install_packages | default(false)
