---
- name: "Developer tools | Ubuntu | Install packages"
  ansible.builtin.apt:
    name:
      - build-essential
      - clang
      - cmake
      - fastfetch
      - hyperfine
      - jq
      - libtool
    state: present
    update_cache: true
  become: true
  when: can_install_packages | default(false)
