---
- name: "Clang | {{ ansible_facts['distribution'] }} | Install packages"
  ansible.builtin.apt:
    name: clang
    state: present
    update_cache: true
  become: true
  when: can_install_packages | default(false)
