---
- name: "Ripgrep | {{ ansible_facts['distribution'] }} | Install packages"
  ansible.builtin.dnf:
    name: ripgrep
    state: present
  become: true
  when: can_install_packages | default(false)
