---
- name: "Tmux | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: tmux_distribution_config

- name: "Tmux | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: tmux_distribution_config.stat.exists

- name: "Tmux | Ensure bin directory exists"
  ansible.builtin.file:
    path: "{{ bin_dir }}"
    state: directory
    mode: "0755"

- name: "Tmux | Configure tmux"
  ansible.builtin.copy:
    src: ".tmux.conf"
    dest: "{{ ansible_facts['user_dir'] }}/.tmux.conf"
    mode: "0644"
    force: true

- name: "Tmux | Install tmux-sessionizer"
  ansible.builtin.copy:
    src: tmux-sessionizer
    dest: "{{ bin_dir }}/tmux-sessionizer"
    mode: "0755"
