---
- name: "Unzip | {{ ansible_facts['distribution'] }} | Install packages"
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: true
  become: true
  when: can_install_packages | default(false)
