#!/usr/bin/env python3
"""Render the Spark SQL builtin function reference into a lua table.

The upstream page is one mkdocs site with a page per category and an <h3> per
function; each section is a signature paragraph, optional Arguments/Examples/Note
blocks and a Since line. Flatten that to markdown so a hover float can show it.

    ./gen-sparkdoc.py > .../dbee/sparkdoc.lua
"""

import html
import re
import sys
import urllib.request

BASE = "https://spark.apache.org/docs/latest/api/sql"


def get(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def categories(index):
    seen = []
    for name in re.findall(r'href="([a-z0-9-]+)/"', index):
        if name not in seen:
            seen.append(name)
    return seen


def text(node):
    """html fragment -> markdown-ish plain text"""
    node = re.sub(r"<pre><code>(.*?)</code></pre>", lambda m: "\x00" + m.group(1) + "\x00", node, flags=re.S)
    node = re.sub(r"<code>(.*?)</code>", r"`\1`", node, flags=re.S)
    node = re.sub(r"<strong>(.*?)</strong>", r"**\1**", node, flags=re.S)
    node = re.sub(r"<em>(.*?)</em>", r"*\1*", node, flags=re.S)
    node = re.sub(r"<li>\s*", "\n- ", node)
    node = re.sub(r"</li>", "\n", node)
    node = re.sub(r"</p>|</ul>|</ol>|<br/?>", "\n\n", node)
    node = re.sub(r"<[^>]+>", "", node)
    node = html.unescape(node)

    # code blocks came through verbatim; fence them, leave the rest wrapped
    out, fenced = [], node.split("\x00")
    for i, chunk in enumerate(fenced):
        if i % 2:
            out.append("```sql\n" + chunk.strip("\n") + "\n```")
        else:
            out.append(re.sub(r"\n{3,}", "\n\n", chunk).strip("\n"))
    node = "\n\n".join(p for p in out if p.strip())
    return re.sub(r"[ \t]+\n", "\n", node).strip()


def functions(page):
    body = re.search(r'<div role="main"[^>]*>(.*)', page, re.S)
    body = body.group(1) if body else page
    # mkdocs slugs operator sections to _1/_2/-; the anchor above the heading
    # keeps the readable name (mod, divide), so prefer it
    parts = re.split(r'<a name="([^"]*)"></a></p>\s*<h3 id="([^"]+)">', body)
    for anchor, slug, chunk in zip(parts[1::3], parts[2::3], parts[3::3]):
        name = anchor or slug
        if not re.fullmatch(r"[a-z_][a-z0-9_]*", name):
            continue
        chunk = re.split(r"<h3|<footer|<div class=\"rst-footer", chunk)[0]
        chunk = re.sub(r"^.*?</h3>", "", chunk, count=1, flags=re.S)
        doc = text(chunk)
        if doc:
            yield name, doc


def lua_str(s):
    out = ['"']
    for ch in s:
        if ch == '"' or ch == "\\":
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 32:
            out.append("\\%d" % ord(ch))
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def quote(s):
    n = 0
    while ("]" + "=" * n + "]") in s:
        n += 1
    eq = "=" * n
    return "[" + eq + "[\n" + s + "]" + eq + "]"


def main():
    index = get(BASE + "/index.html")
    entries = {}
    for cat in categories(index):
        label = cat.replace("-functions", "").replace("-", " ")
        for name, doc in functions(get("%s/%s/" % (BASE, cat))):
            entries.setdefault(name, (label, doc))

    w = sys.stdout.write
    w("-- generated by roles/neovim/scripts/gen-sparkdoc.py -- do not edit\n")
    w("-- source: %s\n\nreturn {\n" % BASE)
    for name in sorted(entries):
        label, doc = entries[name]
        w("  [%s] = { %s, %s },\n" % (lua_str(name), lua_str(label), quote(doc)))
    w("}\n")
    print("%d functions" % len(entries), file=sys.stderr)


main()
