#!/usr/bin/env python3
"""Render the Spark SQL builtin function reference into a lua table.

Each function is an <h3> section holding a signature paragraph, optional
Arguments/Examples/Note blocks and a Since line. 4.0.0 puts them all on one
page; later releases split them into a page per category, so follow whichever
shape the index has.

    ./gen-sparkdoc.py [version] > .../dbee/sparkdoc.lua
"""

import html
import re
import sys
import urllib.request

VERSION = sys.argv[1] if len(sys.argv) > 1 else "4.0.0"
BASE = "https://spark.apache.org/docs/%s/api/sql" % VERSION


def get(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode("utf-8")


def text(node):
    """html fragment -> markdown-ish plain text"""
    node = re.sub(r"<pre><code>(.*?)</code></pre>", lambda m: "\x00" + m.group(1) + "\x00", node, flags=re.S)
    node = re.sub(r"<code>(.*?)</code>", r"`\1`", node, flags=re.S)
    node = re.sub(r"<strong>(.*?)</strong>", r"**\1**", node, flags=re.S)
    node = re.sub(r"<em>(.*?)</em>", r"*\1*", node, flags=re.S)
    node = re.sub(r"<li>\s*", "\n- ", node)
    node = re.sub(r"</li>", "\n", node)
    node = re.sub(r"</p>|</ul>|</ol>|<br/?>", "\n\n", node)
    node = re.sub(r"<[^>]+>", "", node)
    node = html.unescape(node)

    # code blocks came through verbatim; fence them, leave the rest wrapped
    out, fenced = [], node.split("\x00")
    for i, chunk in enumerate(fenced):
        if i % 2:
            out.append("```sql\n" + chunk.strip("\n") + "\n```")
        else:
            out.append(re.sub(r"\n{3,}", "\n\n", chunk).strip("\n"))
    node = "\n\n".join(p for p in out if p.strip())
    return re.sub(r"[ \t]+\n", "\n", node).strip()


def functions(page):
    body = re.search(r'<div role="main"[^>]*>(.*)', page, re.S)
    body = body.group(1) if body else page
    parts = re.split(r'<h3 id="([^"]+)">', body)
    for name, chunk in zip(parts[1::2], parts[2::2]):
        # mkdocs slugs the operator sections to _1/_2/-; every operator that is
        # also callable (mod, div) has a section of its own anyway
        if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
            continue
        chunk = re.split(r"<h3|<footer|<div class=\"rst-footer", chunk)[0]
        chunk = re.sub(r"^.*?</h3>", "", chunk, count=1, flags=re.S)
        doc = text(chunk)
        if doc:
            yield name, doc


def lua_str(s):
    out = ['"']
    for ch in s:
        if ch in '"\\':
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 32:
            out.append("\\%d" % ord(ch))
        else:
            out.append(ch)
    return "".join(out) + '"'


def long_str(s):
    n = 0
    while ("]" + "=" * n + "]") in s:
        n += 1
    eq = "=" * n
    return "[" + eq + "[\n" + s + "]" + eq + "]"


def main():
    index = get(BASE + "/index.html")
    pages = []
    seen = set()
    for cat in re.findall(r'href="([a-z0-9-]+)/"', index):
        if cat not in seen:
            seen.add(cat)
            pages.append("%s/%s/" % (BASE, cat))

    entries = {}
    for page in pages or [BASE + "/index.html"]:
        for name, doc in functions(get(page)):
            entries.setdefault(name, doc)

    w = sys.stdout.write
    w("-- generated by roles/neovim/scripts/gen-sparkdoc.py -- do not edit\n")
    w("-- source: %s\n\nreturn {\n" % BASE)
    w("  version = %s,\n  functions = {\n" % lua_str(VERSION))
    for name in sorted(entries):
        w("    [%s] = %s,\n" % (lua_str(name), long_str(entries[name])))
    w("  },\n}\n")
    print("spark %s: %d functions" % (VERSION, len(entries)), file=sys.stderr)


main()
