---

- name: "{{ role_name }} | Checking for distribution config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: nvim_distribution_config

- name: "{{ role_name }} | Run tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: nvim_distribution_config.stat.exists

- name: "Neovim | Check if nvim config directory exists"
  ansible.builtin.stat:
    path: "{{ config_dir }}/nvim"
  register: nvim_config_stat

- name: "Neovim | Backup existing config if not a symlink"
  when:
    - nvim_config_stat.stat.exists
    - not nvim_config_stat.stat.islnk
  ansible.builtin.command:
    cmd: >
      mv {{ config_dir }}/nvim
         {{ config_dir }}/nvim.backup-{{ ansible_date_time.epoch }}
  args:
    creates: "{{ config_dir }}/nvim.backup-{{ ansible_date_time.epoch }}"

- name: "Neovim | Ensure parent config directory exists"
  ansible.builtin.file:
    path: "{{ config_dir }}"
    state: directory
    mode: "0755"

- name: "Neovim | Symlink ~/.config/nvim -> role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ config_dir }}/nvim"
    state: link
    force: true

- name: "Neovim | Check system TFLint"
  ansible.builtin.stat:
    path: /usr/local/bin/tflint
  register: neovim_system_tflint

- name: "Neovim | Remove duplicate Mason TFLint"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_facts['user_dir'] }}/.local/share/nvim/mason/bin/tflint"
    - "{{ ansible_facts['user_dir'] }}/.local/share/nvim/mason/packages/tflint"
  when: neovim_system_tflint.stat.exists
